export const SET_LANG = "SET_LANG";
export const REMOVE_LANG = "REMOVE_LANG";
export const SELECT_LANG = "SELECT_LANG";

export const FETCH_REPO_PAGE = "FETCH_REPO_PAGE";
export const FETCH_REPO_DATA = "FETCH_REPO_DATA";
export const FETCH_REPO_DATA_FAIL = "FETCH_REPO_DATA_FAIL";
export const FETCH_REPO_DATA_SUCCESS = "FETCH_REPO_DATA_SUCCESS";
export const FETCH_REPO_PAGE_SUCCESS = "FETCH_REPO_PAGE_SUCCESS";

export const ADD_FAVOURITE = "ADD_FAVOURITE";
export const REMOVE_FAVOURITE = "REMOVE_FAVOURITE";

export const SET_ERROR = "SET_ERROR";
export const CLEAR_ERROR = "CLEAR_ERROR";
